### PR TITLE
48/mdx support

### LINKED ISSUE #48: MDX support
It'd be nice if markdown-inject could work with the following synxtax:

```md
{/*
  CODEBLOCK_START
  {
    "type": "command",
    "value": "node -v",
    "hideValue": true
  }
*/}
{/* CODEBLOCK_END */}
```

AS-IS Behavior:

```
Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

### PR DESCRIPTION
**Pull request by nathanyi872**
closes #48 

# Changes

Updated the existing regex to accept both react and HTML comment syntax so that markdown-inject can read either while maintaining that comment syntax does not mix and match and that proper syntax is used

This allows comments in both React and HTML styles to be read in the markdown files which just adds a level of versatility

# Validation

Added testing to ensure that both comment styles are accepted and also added a test to make sure that bad syntax will be rejected (for example: {/*...*/} and  will be accepted while {/*...--> or <!--...*/} will not be)

Created a TESTME.md and TESTME.mdx file to run the markdown-inject script against to ensure that correct HTML and mdx syntax are being used.

TESTME.md:
```
<!-- CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} -->

<!-- CODEBLOCK_END -->
```
ran `npm run build` followed by `node ./dist/index.js TESTME.md` and `TESTME.md` resulted in:
```
<!-- CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} -->
<!-- prettier-ignore -->
~~~~~~~~~~bash
v20.10.0
~~~~~~~~~~
<!-- CODEBLOCK_END -->
```

TESTME.mdx:
```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}

{/* CODEBLOCK_END */}
```

ran `npm run build` followed by `node ./dist/index.js TESTME.mdx` and `TESTME.mdx` resulted in:
```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}
{/* prettier-ignore */}
~~~~~~~~~~bash
v20.10.0
~~~~~~~~~~

{/* CODEBLOCK_END */}
```

Mismatching syntax such as:
```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}


<!-- CODEBLOCK_END -->
```
resulted in errors and did not recognize the CODEBLOCK depending on if it was an `md` or `mdx` file

### CODE REVIEW

File: src/md-inject.ts [hunk 1]
```diff
@@ -76,23 +76,51 @@ const main = async (
...
+            groupName.startsWith(
+              codeblockMatch.groups.html_config ? 'html_' : 'mdx_'
+            )
+          )
+          .map(([groupName, groupValue]) => [
+            groupName.replace(/^(html|mdx)_/, ''),
+            groupValue,
+          ])
+      )
+      console.log(matchGroups)
```
Comment (bmuenzenmeyer) [inline src/md-inject.ts:117]: I imagine we don't want a `console.log` emitting, right?

File: README.md
Comment (bmuenzenmeyer) [inline README.md:1]: are the changes in this file showing that you can mix and match syntax? that seems odd to me

I think the examples should be isolated or exclusive to one style of the syntax at a time.

If we want a self-referential test that MDX works, we should make an MDX file that showcases it. CONTRIBUTING could change, for example.

File: README.md [hunk 2]
```diff
@@ -69,7 +69,7 @@ Options:
 
 `markdown-inject` expands a given glob for markdown files. Then it discovers the below `CODEBLOCK` HTML comments within each markdown file, performs the appropriate action (in this case, reading another local file), and writes content back into the markdown file:
 
-<!-- CODEBLOCK_START_USAGE {"ignore": true} -->
+{/* CODEBLOCK_START_USAGE {"ignore": true} */}
```
Comment (bmuenzenmeyer) [inline README.md:72]: this MDX comment start is... matching the HTML comment end on line 79?

this makes the README actually render the text instead of hiding it

image

File: README.md [hunk 3]
```diff
@@ -79,12 +79,12 @@ Options:
 <!-- CODEBLOCK_END_USAGE -->
 
 ```
-<!-- CODEBLOCK_START {"value": ".nvmrc"} -->
+{/* CODEBLOCK_START {"value": ".nvmrc"} -->
```
Comment (bmuenzenmeyer) [inline README.md:82]: this MDX comment start is matching the HTML comment end on line 90?

File: README.md [hunk 4]
```diff
@@ -69,7 +69,7 @@ Options:
 
 `markdown-inject` expands a given glob for markdown files. Then it discovers the below `CODEBLOCK` HTML comments within each markdown file, performs the appropriate action (in this case, reading another local file), and writes content back into the markdown file:
```
Comment (bmuenzenmeyer) [inline README.md:70]: I think this paragraph should mention CODEBLOCK HTML or MDX comments, as the syntax is distinct

File: .eslintrc.js [hunk 5]
```diff
@@ -14,7 +14,7 @@ module.exports = {
   ],
   rules: {
     // VS Code linting will not respect the `.prettierrc` options unless injected here:
-    'prettier/prettier': ['error', prettierrc],
+    'prettier/prettier': ['warn', prettierrc],
```
Comment (bmuenzenmeyer) [inline .eslintrc.js:17]: good open source PRs try to limit extraneous changes. I appreciate the Node update but can you explain why this change was made? there could be perfectly valid reasons, but without mention it's hard as a reviewer to know

**Review by bmuenzenmeyer — CHANGES_REQUESTED** [review]
Happy to see this taking shape! Thanks for taking it on. I am a bit confused on the PR text and then the README examples, which seem to contradict each other in terms of mixing and matching HTML and MDX syntax. To showcase the MDX support I think we need a real MDX document somewhere in our codebase. I suggested `CONTRIBUTING` because it is smaller and relegates the use case to a secondary file.

Thoughts?

File: .eslintrc.js (hunk 5 above)
Comment (nathanyi872) [reply .eslintrc.js:17]: When Marty and I were editing the file we just didn't want the red squigglies to make it seem like it was broken when it was just prettier. I think I can change that back

File: README.md
Comment (nathanyi872) [reply README.md:1]: Yup that sounds good I changed the comments in the README to match and changed the the CONTRIBUTING file to an mdx and used the MDX comment syntax for the codeblock

**Comment by ckemp1** [comment]
>To showcase the MDX support I think we need a real MDX document somewhere in our codebase. I suggested CONTRIBUTING because it is smaller and relegates the use case to a secondary file.

I noticed that the contributing file was removed in your recent commit, and doesn't appear to exist anymore, was this intentional? Maybe the mdx altered `Contributing` file wasn't staged to your most recent commit?

>Yup that sounds good I changed the comments in the README to match and changed the the CONTRIBUTING file to an mdx and used the MDX comment syntax for the codeblock

File: CONTRIBUTING.md
Comment (ckemp1) [inline CONTRIBUTING.md:1]: >To showcase the MDX support I think we need a real MDX document somewhere in our codebase. I suggested CONTRIBUTING because it is smaller and relegates the use case to a secondary file.

I noticed that the contributing file was removed in your recent commit, and doesn't appear to exist anymore, was this intentional? Maybe the mdx altered `Contributing` file wasn't staged to your most recent commit?

>Yup that sounds good I changed the comments in the README to match and changed the the CONTRIBUTING file to an mdx and used the MDX comment syntax for the codeblock

File: README.md [hunk 6]
```diff
@@ -67,7 +67,7 @@ Options:
 
 <!-- CODEBLOCK_END -->
 
-`markdown-inject` expands a given glob for markdown files. Then it discovers the below `CODEBLOCK` HTML comments within each markdown file, performs the appropriate action (in this case, reading another local file), and writes content back into the markdown file:
+`markdown-inject` expands a given glob for markdown files. Then it discovers the below `CODEBLOCK` HTML or MDX comments within each markdown file, performs the appropriate action (in this case, reading another local file), and writes content back into the markdown file:
```
Comment (ckemp1) [inline README.md:70]: Could we mention the `Contributing.mdx` file as an example that mdx comments are now supported?

**Comment by ckemp1** [comment]
After a quick glance through the tests and file changes, I don't see a test specifically for the mdx comment case. For example, there's an exisiting case for html:
```
it('writes to the markdown document (command)', async () => {
    mock({
      config: {
        type: 'command',
        value: 'some arbitrary command',
      },
      mockResponse: 'The output of some arbitrary command',
    })

    await injectMarkdown()

    const outFile = `
<!-- CODEBLOCK_START {"type":"command","value":"some arbitrary command"} -->
<!-- prettier-ignore -->
~~~~~~~~~~bash
$ some arbitrary command

The output of some arbitrary command
~~~~~~~~~~

<!-- CODEBLOCK_END -->`
    expect(fs.writeFile).toHaveBeenCalledWith('foo.md', outFile)
  })

```

I believe it would be appropriate to add in another case for mdx comment styling. 

The reason for why I bring this up, is because I think there's an error when using mdx comments. 

Here's an example using the following `test.mdx` file:
```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}

{/* CODEBLOCK_END */}
```
I get the following after running the inject script locally with the added changes

```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}
<!-- prettier-ignore -->
~~~~~~~~~~bash
20.10.0
~~~~~~~~~~

{/* CODEBLOCK_END */}
```

Which I'm assuming is not what we would want. We want the output to also use the same mdx comment syntax, but instead it seems to be still adding in html styled comments, instead of this?

```
{/* CODEBLOCK_START {"value": ".nvmrc", "hideValue": true} */}
{/* prettier-ignore */}
~~~~~~~~~~bash
20.10.0
~~~~~~~~~~

{/* CODEBLOCK_END */}
```

File: src/__tests__/md-inject.test.ts [hunk 7]
```diff
@@ -312,6 +319,60 @@ The output of some arbitrary command
...
+        value: 'some arbitrary command',
+      },
+      mockResponse: 'The output of some arbitrary command',
+    })
+
+    await injectMarkdown()
+
+    const outFile = `
+{/* CODEBLOCK_START {"type":"command","value":"some arbitrary command"} */}
+<!-- prettier-ignore -->
```
Comment (bmuenzenmeyer) [inline src/__tests__/md-inject.test.ts:336]: building on @ckemp1's excellent review, I think this is also a stray HTML style comment within an MDX file, and it's presence here (and passing test) would indicate that this is perhaps still not working? I didn't run it locally yet, but wanted to note this.

Comment (ckemp1) [reply src/__tests__/md-inject.test.ts]: We've been chatting back and forth, and that issue should be resolved now. All there is left to tackle would be my first concern when running the script itself
>We want the output to also use the same mdx comment syntax, but instead it seems to be still adding in html styled comments

Comment (nathanyi872) [reply src/__tests__/md-inject.test.ts]: This issue has now been resolved and verified and is explained in the PR body

**Review by bmuenzenmeyer — APPROVED** [review]

**Review by ckemp1 — APPROVED** [review]
